### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by hbsun2113** [EINDEX/leetcode-spider-go#3]
![image](https://user-images.githubusercontent.com/27994442/57684444-5f5b3500-7668-11e9-84f0-02523223879e.png)
![image](https://user-images.githubusercontent.com/27994442/57684478-74d05f00-7668-11e9-8aa4-62a5ed2c2861.png)

**Comment by EINDEX** [comment]
你好 感谢你的使用.
第一张图中的错误 是登陆失败.
第二张图中的错误 是你没有设置 GOPATH 环境变量.

**Comment by EINDEX** [comment]
#4
